---
Name: genealogist
---

GenealogistHelper:
  access_groups:
    - administrators
    - librarians
    - genealogists
    - co-genealogists
    
Person:
  extensions:
    - PersonCMSExtension
    - PersonGetterExtension
    - PersonUtilsExtension
    - PersonUIExtension
      
