---
Name: genealogist
---

GenealogistHelper:
  access_groups:
    - administrators
    - librarians
    - genealogists
    - co-genealogists
      
Person:
  extensions:
    - DataObject_MemberExtension
      
Town:
  extensions:
    - DataObject_MemberExtension
